name: Build & push Docker image

on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*'
      - '*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            bitergia/bitergia-analytics-opensearch-dashboards
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      -
        name: Install Cosign
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b # v2.8.1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Sign image with a key
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY ${TAGS}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
